version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20  # Node.js version updated to 18
    commands:
      - npm install
  pre_build:
    commands:
      - echo Fetching env variables from SSM...
  build:
    commands:
      - ls
      - npm run build
artifacts:
  files:
      - '**/*'
  base-directory: 'build*'
  discard-paths: no
